Use case of Pandas - 

Data Cleaning
Data Analysis 
Data Transformation
Data Visualization
Data Aggregation
File Handling
Data Filtering & Selection
Time Series Analysis

Series

A series is a one dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

Creating Series

In [2]:
import numpy as np
import pandas as pd

In [3]:
#labels also called index
labels = ['a','b','c']
my_list = [10,20,30];
arr = np.array([10,20,30])
d = {1:10, 2:20, 3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr) # only 1 dim

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

DataFrame - When we combine multiple series it forms Dataframe

In [8]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [9]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [11]:
df2 = pd.DataFrame(data_list)

In [12]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [13]:
columns = ["Name", "Age", "City", "Salary"]

In [16]:
df2 = pd.DataFrame(data_list,columns=columns)

In [17]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selction and Indexing

In [19]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [20]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a New Column

In [21]:
df2['Designation'] = ['Doctor','Engineer','Doctor','Engineer']

In [22]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

Removing a Column

In [ ]:
df2.drop('Designation', axis=1) # This is not inplace
# Axis - 0 is by default which works on the row label, while axis - 1 works on column label

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [27]:
df2 = df2.drop('Designation', axis=1)

In [28]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.drop(['City', 'Salary'], axis = 1, inplace=False)
# inplace lets delete in place

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [30]:
df2 = df2.drop(0, axis=0)

In [31]:
df2

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [33]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df = pd.DataFrame(data_list, columns=columns)

In [34]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.loc[0]
# to extract rows

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [37]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [38]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subsets of Row and Columns

In [39]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [41]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

Conditional Selection

In [42]:
# Age is above 30
df[df['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [45]:
df[(df['Age'] > 30) & (df['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

Missing Data

In [57]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [58]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [59]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [60]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [61]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Removing Missing Data

In [62]:
df.dropna()
# Row with even a single null value will be deleted

     A  B    C    D
0  1.0  1  1.0  1.0

In [64]:
df.dropna(thresh=3)
# Atmost 3 non null honi chahiye

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Filling the missing data

In [65]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values = {
    'A' : 0,
    'B': 100,
    'C': 300,
    'D': 400
}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [69]:
# Drop happens row wise
# Selection and filling happens column wise

In [70]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [71]:
# Now I want to fill through mean of data
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0